team_builder/accounts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('logout/', views.LogOutView.as_view(), name='signout')

]

team_builder/team_builder/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from user_profile import views

urlpatterns = [
    path('', views.index, name="index"),

                  path('admin/', admin.site.urls),
    path('accounts/', include(("accounts.urls", 'accounts'), namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('profile/', include(("user_profile.urls", 'profile'), namespace="profile"))


]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

team_builder/user_profile/urls.py
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns =\
    [
        path('<int:pk>', views.MyProfileView.as_view(), name='my_profile'),
        path('<int:pk>/edit/', views.profile_edit, name='profile-update'),

        path('project/<int:pk>/', views.ProjectView.as_view(), name='project'),
        path('project/<int:pk>/update/', views.edit_project, name='project-update'),
        path('project/<int:pk>/delete/', views.delete_project, name='delete-project'),

        path('project/<int:project_pk>/apply/<int:position_pk>/', views.apply_position, name='apply_position'),
        path('applications/applicant/<int:applicant_pk>/reject', views.reject_application,
             name='reject_application'),

        path('applications/applicant/<int:applicant_pk>/accept', views.accept_application,
             name='accept_application'),

        path('create_project/', views.create_project, name='create_project'),
        path('search_project/', views.ProjectListView.as_view(), name='search_project'),

        path('notifications', views.NotificationsView.as_view(), name="notifications"),

        path('all-applications/', views.ApplicationsView.as_view(), name='all_applications'),
        path('new-applications/', views.NewApplicationsView.as_view(), name='new_applications'),
        path('rejected-applications/', views.RejectedApplicationsView.as_view(), name='rejected_applications'),
        path('accepted-applications/', views.AcceptedApplicationsView.as_view(), name='accepted_applications'),
        path('filter-projects/<str:position>/', views.FilterProjectsView.as_view(), name='filter-projects'),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

team_builder/user_profile/models.py
from django.db import models

from django.contrib.auth.models import User
from django.urls import reverse

from team_builder import settings
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    profile_skill = models.CharField(max_length=50,)

    @receiver(post_save, sender=settings.AUTH_USER_MODEL)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=settings.AUTH_USER_MODEL)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    def get_absolute_url(self):
        return reverse('profile:my_profile')


class Project(models.Model): #article
    project_skill = models.CharField(max_length=400)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    description = models.TextField(max_length=300)
    title = models.CharField(max_length=100)
    timeline = models.CharField(max_length=20)

    def __str__(self):
        return self.title


class ProjectPosition(models.Model):
    #one project can have many positions
    project = models.ForeignKey(Project, on_delete=models.CASCADE,)
    title = models.CharField(max_length=300, blank=True)
    information = models.TextField(max_length=300, blank=True)
    apply = models.BooleanField(default=False)
    timeline = models.CharField(max_length=20)
    filled = models.BooleanField(default=False)
    description = models.TextField(max_length=300)

    def __str__(self):
        return self.title


class Applicant(models.Model):

    ACCEPTED = 'a'
    REJECTED = 'r'
    PENDING = 'p'
    STATUS_CHOICES = (
        (ACCEPTED, 'Accepted'),
        (REJECTED, 'Rejected'),
        (PENDING, 'Pending'),
    )

    name = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES,)
    position = models.ForeignKey('ProjectPosition', on_delete=models.CASCADE)


class ProfileSkill(models.Model):
    skill_name = models.CharField(max_length=50, blank=True)
    # one profile can have many skills
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE,)

    def __str__(self):
        return self.skill_name


class ProjectSkill(models.Model):
    name = models.CharField(max_length=50)
    # one profile can have many skills
    project = models.ForeignKey(Project, on_delete=models.CASCADE,)

    def __str__(self):
        return self.name

team_builder/user_profile/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.forms import ModelForm, Textarea, TextInput

from django.contrib.auth.forms import UserChangeForm
from django.utils.safestring import mark_safe
from django.forms import widgets
from django.conf import settings
from django.forms.models import inlineformset_factory, modelformset_factory

from .models import Profile, Project, ProjectPosition, ProfileSkill, ProjectSkill


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
            'bio',
        )





class EditUserForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ("username", "avatar")


class CreateProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ("title", 'description', 'timeline', 'project_skill')
        label = {'title': 'Project Title'}

    widgets = {
        'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'projectname here'}),
        'description': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'description'}),
        'timeline': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'timeline'}),
        'project_skill': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'skill'}),

    }


PositionModelFormset = modelformset_factory(
    ProjectPosition,
    fields=('title', 'information',),
    extra=3,
    max_num=3,
    widgets={
        'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'title!'}),
        'information': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'information!'}),

    }
)

SkillModelFormset = modelformset_factory(
    ProfileSkill,
    fields=('skill_name',),
    extra=3,
    max_num=3,
    widgets={
        'skill_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'name!'}),

    }
)

team_builder/user_profile/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import DetailView, ListView
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from notifications.signals import notify
from django.contrib.auth.models import User
from .models import Project, ProjectPosition, Applicant, ProfileSkill, Profile

from . import forms


def index(request,):
    """homepage"""
    projects = Project.objects.filter()
    return render(request, 'index.html', {'projects': projects})


@login_required
def profile_edit(request, pk):
    """allows user to edit their personal profile"""
    instance = get_object_or_404(Profile, pk=pk)
    skill_instance = ProfileSkill.objects.filter(profile__user_id=instance.id)

    if request.user.pk == instance.user.pk:

        if request.method == 'POST':
            profile_form = forms.EditProfileForm(request.POST, instance=instance)
            user_form = forms.EditUserForm(request.POST, request.FILES, instance=instance.user)
            skill_formset = forms.SkillModelFormset(request.POST, queryset=skill_instance)

            if profile_form.is_valid() and user_form.is_valid() and skill_formset.is_valid():
                user_form.save()
                profile = profile_form.save(commit=False)

                # more than one skill can be added in the profile.
                for form in skill_formset:
                    skill = form.save(commit=False)
                    skill.profile = profile
                    skill.save()
                return redirect('profile:my_profile', pk=request.user.pk)

        else:
            profile_form = forms.EditProfileForm(instance=instance)
            user_form = forms.EditUserForm(request.POST or None, instance=instance.user)
            skill_formset = forms.SkillModelFormset(request.POST or None, queryset=skill_instance)

        return render(request,
                      'user_profile/profile_edit.html',
                      {'profile_form': profile_form,
                       'user_form': user_form,
                       'skill_formset': skill_formset,
                       }
                      )


class MyProfileView(LoginRequiredMixin, DetailView):
    """Shows the profile page for logged in user"""
    template_name = 'user_profile/profile.html'
    context_object_name = 'profile'

    def get_object(self, queryset=None):
        return Profile.objects.get(pk=self.kwargs.get('pk'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['skills'] = ProfileSkill.objects.filter(profile__user_id=self.kwargs.get('pk'))
        context['projects'] = Project.objects.filter(owner_id=self.kwargs.get('pk'))
        context['applicants'] = Applicant.objects.filter(Q(name_id=self.kwargs.get('pk')) &
                                                                  (Q(status='a')))
        return context


class ProjectView(LoginRequiredMixin, DetailView):
    """shows the project the user requested to view"""
    template_name = 'user_profile/project.html'

    def get_object(self, queryset=None):
        return get_object_or_404(Project, pk=self.kwargs.get('pk'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['positions'] = ProjectPosition.objects.filter(project__id=self.kwargs.get('pk'))
        context['project'] = Project.objects.get(pk=self.kwargs.get('pk'))
        return context


class ApplicationsView(LoginRequiredMixin, ListView):
    """shows all applicants for projects the logged in user created"""
    template_name = 'user_profile/applications.html'
    model = Applicant

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['applicants'] = Applicant.objects.filter(position__project__owner_id=self.request.user.id)
        context['projects'] = Project.objects.filter(owner=self.request.user)
        return context


class NewApplicationsView(LoginRequiredMixin, ListView):
    """shows all applicants that haven't been accepted or rejected for projects the logged in user created"""
    template_name = 'user_profile/applications.html'
    model = Applicant

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['applicants'] = Applicant.objects.filter(Q(position__project__owner_id=self.request.user.id) &
                                                             (Q(status='p')))
        context['projects'] = Project.objects.filter(owner=self.request.user)

        return context


class AcceptedApplicationsView(LoginRequiredMixin, ListView):
    """shows all applicants that have been accepted for projects the logged in user created"""

    template_name = 'user_profile/applications.html'
    model = Applicant

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['applicants'] = Applicant.objects.filter(Q(position__project__owner_id=self.request.user.id) &
                                                                  (Q(status='a')))
        context['projects'] = Project.objects.filter(owner=self.request.user)

        return context


class RejectedApplicationsView(LoginRequiredMixin, ListView):
    """shows all applicants that have been rejected for projects the logged in user created"""

    template_name = 'user_profile/applications.html'
    model = Applicant

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['applicants'] = Applicant.objects.filter(Q(position__project__owner_id=self.request.user.id) &
                                                                  (Q(status='r')))

        context['projects'] = Project.objects.filter(owner=self.request.user)

        return context


@login_required
def create_project(request):
    """allows users to create a project"""
    if request.method == 'POST':
        project_form = forms.CreateProjectForm(request.POST, prefix='project')
        position_formset = forms.PositionModelFormset(request.POST, prefix='position')

        if project_form.is_valid() and position_formset.is_valid():

            project = project_form.save(commit=False)
            project.owner = request.user
            project.save()

            # more than one position can be added to the project.
            for form in position_formset:
                position = form.save(commit=False)
                position.project = project
                position.save()
            return redirect('profile:my_profile', pk=request.user.pk)

    else:
        position_formset = forms.PositionModelFormset(queryset=ProjectPosition.objects.none(), prefix='position')
        project_form = forms.CreateProjectForm(prefix='project')

    return render(request, 'user_profile/project_new.html',
                  {'project_form': project_form,
                   'position_formset': position_formset}
                  )


@login_required
def edit_project(request, pk):
    """allows user to edit a project"""
    project = get_object_or_404(Project, pk=pk)
    position = ProjectPosition.objects.filter(project__id=pk)

    if request.user == project.owner:

        if request.method == 'POST':
            position_formset = forms.PositionModelFormset(request.POST, queryset=position, prefix='position')
            project_form = forms.CreateProjectForm(request.POST, instance=project, prefix='project')

            if project_form.is_valid() and position_formset.is_valid():

                project = project_form.save(commit=False)
                project.owner = request.user
                project.save()

                # more than one position can be added to the project.
                for form in position_formset:
                    position = form.save(commit=False)
                    position.project = project
                    position.save()
                return redirect('profile:project', pk=pk)

        else:
            project_form = forms.CreateProjectForm(instance=project, prefix='project')
            position_formset = forms.PositionModelFormset(queryset=position, prefix='position')

        return render(request,
                      'user_profile/project_edit.html',
                      {'project_form': project_form,
                       'position_formset': position_formset,
                       }
                      )


@login_required
def delete_project(request, pk):
    """allows user to delete a project"""
    project = get_object_or_404(Project, pk=pk)
    if request.user == project.owner:
        project.delete()
        return redirect('profile:my_profile', pk=request.user.pk)


@login_required
def apply_position(request, project_pk, position_pk):
    """allows user to apply for a position in a project"""
    project = get_object_or_404(Project, pk=project_pk)
    positions = ProjectPosition.objects.filter(project__id=project.pk,)
    for position in positions:

        if position.pk == position_pk:
            for applicant in position.applicant_set.filter():
                # # prevents user to apply more than once directly via the link
                if applicant.name.pk == request.user.pk:
                    raise Exception ('You have already applied for this position!')

            pending_status = position.applicant_set.create(status='p', name=request.user)
            pending_status.save()
            return redirect('profile:project', pk=project.pk)


@login_required
def reject_application(request, applicant_pk):
    """allows the project owner to reject an application"""
    applicant = get_object_or_404(Applicant, pk=applicant_pk)
    applicant.status = 'r'
    applicant.save()

    notify.send(
        applicant.name,
        recipient=applicant.name,

team_builder/user_profile/templates/user_profile/applications.html
{% extends 'layout.html' %}

{% block body_content %}

  <div class="bounds circle--page">
    <div class="circle--page--header grid-100">
      <h2>Applications</h2>
    </div>

    <div class="grid-25">
      <div class="circle--filter circle--secondary--module">
        <h4>Status</h4>
        <ul class="circle--filter--list">
          <li><a {% if 'all-' in request.path %} class="selected"{% endif %} href="{% url 'profile:all_applications' %}">All Applications</a></li>
          <li><a {% if 'new-' in request.path %} class="selected"{% endif %} href="{% url 'profile:new_applications' %}">New Applications</a></li>
          <li><a {% if 'accepted-' in request.path %} class="selected"{% endif %} href="{% url 'profile:accepted_applications' %}">Accepted</a></li>
          <li><a {% if 'rejected-' in request.path %} class="selected"{% endif %} href="{% url 'profile:rejected_applications' %}">Rejected</a></li>
        </ul>
      </div>

      <div class="circle--filter circle--secondary--module">
        <h4>My Projects</h4>
        <ul class="circle--filter--list">
          <li><a class="selected">All Projects</a></li>
          {% for project in projects %}
          <li><a href="{% url 'profile:project' pk=project.pk %}">{{ project }}</a></li>
          {% endfor %}
        </ul>
      </div>

    </div>

    <div class="grid-70 grid-push-5">
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Applicant</th>
            <th class="circle--cell--right">Applicant Position</th>
            <th class="circle--cell--right">Status</th>
          </tr>
        </thead>
        <tbody>
          {% for applicant in applicants %}
            {% if applicant.position.project.owner == request.user %}
                {% if applicant.position.title %}

          <tr class="clickable-row">
            <td>
              <h3><a href="{% url 'profile:my_profile' pk=applicant.name.pk %}">{{ applicant.name.username }}</a> </h3>
              <p><a href="{% url 'profile:project' applicant.position.project.pk %}">{{ applicant.position.project.title }}</a></p>
            </td>
            <td class="circle--cell--right">
              <span class="secondary-label">{{ applicant.position.title }}</span>
            </td>
              <td class="circle--cell--right">
                {% if applicant.status == 'p' %}
                <a class="button icon-on-left" href="{% url 'profile:accept_application' applicant_pk=applicant.pk %}">Accept</a> -
                <a class="button icon-on-left" href="{% url 'profile:reject_application' applicant_pk=applicant.pk %}">Reject</a>
                {% elif applicant.status == 'a' %}
                <a class="button icon-on-left"><font color= "green"> Accepted</font></a>
                {% elif applicant.status == 'r' %}
                <a class="button icon-on-left"><font color= "red">Rejected</font></a>
                {% endif %}
              {% endif %}
            </td>
            {% endif %}
          </tr>

        {% endfor %}


        </tbody>

      </table>

    </div>

  </div>
{% endblock %}

team_builder/user_profile/templates/user_profile/filter_projects.html
{% extends 'layout.html' %}

{% block body_content %}

<div class="bounds circle--page">


<h2>Projects</h2>
      <table class="u-full-width circle--table">

        <thead>
          <tr>
            <th>Project Title</th>
            <th class="circle--cell--right">Project Description</th>
          </tr>
        </thead>

        {% for project in projects %}
        <tbody>
          <tr class="clickable-row">
            <td>
              <h3><a href="{% url 'profile:project' pk=project.pk %}"> {{ project.title }}</a></h3>
            </td>
            <td class="circle--cell--right">
              <span class="secondary-label">{{ project.description }}</span>
            </td>
          </tr>
        </tbody>
          {% endfor %}
      </table>

    </div>
{% endblock body_content %}

team_builder/user_profile/templates/user_profile/notifications.html
{% extends 'layout.html' %}

{% block body_content %}
  <div class="bounds circle--page">

      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Notifications</th>
          </tr>
        </thead>
        <tbody>
    {% for notice in request.user.notifications.unread %}
          <tr class="clickable-row">
            <td>
              <h3>>{{ notice }}</h3>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>


{% endblock %}

team_builder/user_profile/templates/user_profile/profile.html
{% extends 'layout.html' %}

{% load notifications_tags %}

{% block body_content %}
<body>
  <div class="bounds circle--page">
    <div class="circle--page--header circle--fluid">

      <div class="circle--fluid--cell circle--fluid--primary">
        <h2>Profile</h2>
      </div>
      <div class="circle--fluid--cell circle--fluid--secondary">
        {% if profile.user.pk == request.user.pk %}
        <a class="button icon-on-left" href="{% url 'profile:profile-update' profile.user.pk  %}">Edit</a>
        {% endif %}
      </div>
    </div>


    <div class="grid-70">
      <h1>{{ profile.user.username }}</h1>
      <div class="circle--article--body">
        <p>{{ profile.bio }}</p>
      </div>

      <h2>Current Projects</h2>
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Project Title</th>
            <th class="circle--cell--right">Project Needs</th>
          </tr>
        </thead>
        <tbody>
          {% for project in applicants %}
          <tr class="clickable-row">
            <td>
              <h3>{{ project.position.project.title }}</h3>
            </td>
            <td class="circle--cell--right">
              <span class="secondary-label">{{ project.position.project.description|slice:":1" }}</span>
            </td>
            {% endfor %}
          </tr>

        </tbody>
      </table>
    </div>

    <div class="grid-25 grid-push-5">

      <div class="circle--secondary--module">
          {% if profile.user.avatar %}
          <img src="{{ object.user.avatar.url }}" width="248">
          {% endif %}
      </div>

      <div class="circle--secondary--module">
        <h4>My Skills</h4>
        {% for skill in skills %}
        <ul class="unloaded">
          <li>{{ skill.skill_name }}</li>
        </ul>
        {% endfor %}
      </div>

      <div class="circle--secondary--module">
        <h4>{{ profile.user.username }}'s Projects</h4>
        {% if profile.user.pk == request.user.pk %}
          <a class="button icon-on-left" href="{% url 'profile:create_project'  %}">Create Project</a>
        {% endif %}
        {% for project in projects %}
        <ul class="circle--link--list">
          <li><a href="{% url 'profile:project' pk=project.pk %}">{{ project.title }}</a></li>
        </ul>
          {% endfor %}

      </div>
    </div>

  </div>
</body>
{% endblock %}

team_builder/user_profile/templates/user_profile/profile_edit.html
{% extends 'layout.html' %}

{% load staticfiles %}

{% block body_content %}

<form method="POST" enctype="multipart/form-data">
{% csrf_token %}


  <div class="bounds circle--page">
    <div class="circle--page--header circle--fluid">
      <div class="circle--fluid--cell circle--fluid--primary">
        <h2>Profile</h2>
      </div>
      <div class="circle--fluid--cell circle--fluid--secondary">
        <button type="submit" class="button button-primary icon-on-left">Save Changes</button>
      </div>
    </div>


    <div class="grid-70">
        {{user_form.username}}
      <div class="circle--article--body">
          {{ profile_form.bio }}
      </div>

      <h2>Current Projects</h2>
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Project Title</th>
            <th class="circle--cell--right">Project Needs</th>
          </tr>
        </thead>
        <tbody>
          <tr class="clickable-row">
            {% for project in applicants %}
            <td>
              <h3>{{ project.position.project.title }}</h3>
            </td>
            <td class="circle--cell--right">
              <span class="secondary-label">{{ project.position.project.description  }}</span>
            </td>
            {% endfor %}
          </tr>

        </tbody>
      </table>
    </div>

    <div class="grid-25 grid-push-5">
      <div class="circle--secondary--module">
        <div class="circle--primary--avatar">
            {{ user_form.avatar }}
        </div>
      </div>

      <div class="circle--secondary--module">
        <h4>My Skills</h4>
        You can add 3 skills.
        <ul class="circle--clone--list">
            {% for skill_form in skill_formset %}
              {% for hidden in skill_form.hidden_fields %}
                {{ hidden }}
              {% endfor %}
            <li>
            {{ skill_formset.management_form }}
            {{ skill_form.errors }}
            {{ skill_form.skill_name }}
          </li>
            {% endfor %}
        </ul>
      </div>
    </div>

  </div>
  </form>

{% endblock %}

team_builder/user_profile/templates/user_profile/project.html
{% extends 'layout.html' %}

{% load staticfiles %}

{% block body_content %}

  <div class="circle--actions--bar">
    <div class="bounds">
      <div class="grid-100">
        {% if request.user.pk == project.owner.pk %}
        <a class="button" href="{% url 'profile:project-update' pk=project.pk %}">Edit Project</a>
        <a class="button button-text" href="{% url 'profile:delete-project' pk=project.pk %}">Delete Project</a>
        {% endif %}
      </div>
    </div>
  </div>

  <div class="bounds circle--page circle--article">
    <div class="grid-70">
      <div class="circle--article--header">
        <h4 class="circle--article--section">Project</h4>
        <h1 class="circle--article--title">{{ project.title }}</h1>
        <p class="circle--article--byline">Project Owner: <a>{{ project.owner }}</a></p>
      </div>

      <div class="circle--article--body">
        <p>{{ project.description }}</p>


      </div>

      <div class="circle--project--positions">

        <h2>Positions</h2>
        {% for position in positions %}
        {% if position.title and position.information %}

        <ul class="circle--group--list">
          <li>
            <h3>{{ position.title }}</h3>
            <p>{{ position.information }}</p>

            {% if project.owner == request.user %}
              <a class="button button-primary"  href="">You are the owner of this project</a>

            {% elif position.filled %}
              <a class="button button-primary"  href="">Position is already filled</a>

            {% elif position.applicant_set.all %}
              {% for applicant in position.applicant_set.all %}
                {% if applicant.name == request.user %}
            <a class="button button-primary"  href="">You have already applied for this position</a>
                {% endif %}
              {% endfor %}

            {% else %}
            <a class="button button-primary"  href="{% url 'profile:apply_position' project.pk position.pk %}">Apply</a>
            {% endif %}
          </li>
            {% endif %}

        </ul>
        {% endfor %}

      </div>
    </div>


    <div class="grid-25 grid-push-5">
      <div class="circle--secondary--module">
        <h3>Project Needs</h3>
        <ul class="circle--link--list">
        {% for position in project.projectposition_set.all %}
         <p>{{ position }}</p>
        </ul>
        {% endfor %}
      </div>

      <div class="circle--secondary--module">
        <h3>Project Timeline</h3>
        <p>{{ project.timeline }}</p>
      </div>

      <div class="circle--secondary--module">
        <h3>Project Skill</h3>
        <p>{{ project.project_skill }}
      </div>

    </div>
  </div>

{% endblock %}

team_builder/user_profile/templates/user_profile/project_edit.html
{% extends 'layout.html' %}

{% block body_content %}

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}


  <div class="circle--actions--bar">
    <div class="bounds">
      <div class="grid-100">
        <button type="submit" class="button button-primary">Save Changes</button>
        <a class="button button-text" href="{% url 'index' %}">Discard</a>
      </div>
    </div>
  </div>

  <div class="bounds circle--page circle--article">
    <div class="grid-70">
      <div class="circle--article--body">
        {{ project_form.errors }}
        {{ project_form.title.label }}:
        <p>{{ project_form.title }}</p>
        {{ project_form.description.label }}:
        <p> {{ project_form.description }}</p>
      </div>

      <div class="circle--project--positions">
        <h2>Positions</h2>
          You can add up to 3 positions.

        {{ position_formset.management_form }}

        <ul class="circle--group--list circle--clone--list">
            {% for form in position_formset %}
              {% for hidden in form.hidden_fields %}
                {{ hidden }}
              {% endfor %}
            <li>
          <h3>Position Title</h3>
              {{ position_formset.management_form }}
              {{ form.title.errors}}
              {{ form.title }}
          <h3>Position Information</h3>
            {{ position_formset.management_form }}
            {{ form.information.errors }}
            {{ form.information }}
          </li>
        {% endfor %}
        </ul>

      </div>
    </div>

    <div class="grid-25 grid-push-5">

      <div class="circle--secondary--module">
        <h3>{{ project_form.timeline.label }}:</h3>
        {{ project_form.timeline }}
      </div>


      <div class="circle--secondary--module">
        <h3>Skill</h3>
        {{ project_form.project_skill }}
      </div>

    </div>
  </div>
</form>
{% endblock %}