team_builder/accounts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('logout/', views.LogOutView.as_view(), name='signout')

]

team_builder/team_builder/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from user_profile import views

urlpatterns = [
    path('', views.index, name="index"),

                  path('admin/', admin.site.urls),
    path('accounts/', include(("accounts.urls", 'accounts'), namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('profile/', include(("user_profile.urls", 'profile'), namespace="profile"))


]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

team_builder/user_profile/urls.py
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns =\
    [
        path('<int:pk>', views.MyProfileView.as_view(), name='my_profile'),
        path('<int:pk>/edit/', views.profile_edit, name='profile-update'),

        path('project/<int:pk>/', views.ProjectView.as_view(), name='project'),
        path('project/<int:pk>/update/', views.edit_project, name='project-update'),
        path('project/<int:pk>/delete/', views.delete_project, name='delete-project'),

        path('project/<int:project_pk>/apply/<int:position_pk>/', views.apply_position, name='apply_position'),
        path('applications/applicant/<int:applicant_pk>/reject', views.reject_application,
             name='reject_application'),

        path('applications/applicant/<int:applicant_pk>/accept', views.accept_application,
             name='accept_application'),

        path('create_project/', views.create_project, name='create_project'),
        path('search_project/', views.ProjectListView.as_view(), name='search_project'),

        path('notifications', views.NotificationsView.as_view(), name="notifications"),

        path('all-applications/', views.ApplicationsView.as_view(), name='all_applications'),
        path('new-applications/', views.NewApplicationsView.as_view(), name='new_applications'),
        path('rejected-applications/', views.RejectedApplicationsView.as_view(), name='rejected_applications'),
        path('accepted-applications/', views.AcceptedApplicationsView.as_view(), name='accepted_applications'),
        path('filter-projects/<str:position>/', views.FilterProjectsView.as_view(), name='filter-projects'),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

team_builder/user_profile/models.py
from django.db import models

from django.contrib.auth.models import User
from django.urls import reverse

from team_builder import settings
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    profile_skill = models.CharField(max_length=50,)

    @receiver(post_save, sender=settings.AUTH_USER_MODEL)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=settings.AUTH_USER_MODEL)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    def get_absolute_url(self):
        return reverse('profile:my_profile')


class Project(models.Model): #article
    project_skill = models.CharField(max_length=400)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    description = models.TextField(max_length=300)
    title = models.CharField(max_length=100)
    timeline = models.CharField(max_length=20)

    def __str__(self):
        return self.title


class ProjectPosition(models.Model):
    #one project can have many positions
    project = models.ForeignKey(Project, on_delete=models.CASCADE,)
    title = models.CharField(max_length=300, blank=True)
    information = models.TextField(max_length=300, blank=True)
    apply = models.BooleanField(default=False)
    timeline = models.CharField(max_length=20)
    filled = models.BooleanField(default=False)
    description = models.TextField(max_length=300)

    def __str__(self):
        return self.title


class Applicant(models.Model):

    ACCEPTED = 'a'
    REJECTED = 'r'
    PENDING = 'p'
    STATUS_CHOICES = (
        (ACCEPTED, 'Accepted'),
        (REJECTED, 'Rejected'),
        (PENDING, 'Pending'),
    )

    name = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES,)
    position = models.ForeignKey('ProjectPosition', on_delete=models.CASCADE)


class ProfileSkill(models.Model):
    skill_name = models.CharField(max_length=50, blank=True)
    # one profile can have many skills
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE,)

    def __str__(self):
        return self.skill_name


class ProjectSkill(models.Model):
    name = models.CharField(max_length=50)
    # one profile can have many skills
    project = models.ForeignKey(Project, on_delete=models.CASCADE,)

    def __str__(self):
        return self.name

team_builder/templates/index.html
{% extends 'layout.html' %}

{% block body_content %}

  <div class="bounds circle--page">
    <div class="circle--page--header circle--fluid">
      <div class="circle--fluid--cell circle--fluid--primary">
        <h2>Projects</h2>
      </div>
      <div class="circle--fluid--cell circle--fluid--secondary">
        <a class="button button-primary icon-on-left" href="{% url 'profile:create_project' %}">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 13 13" style="enable-background:new 0 0 13 13;" xml:space="preserve" class="add">
            <polygon points="7,6 7,0 6,0 6,6 0,6 0,7 6,7 6,13 7,13 7,7 13,7 13,6 "/>
          </svg>
          New Project
        </a>
      </div>
    </div>

    <div class="grid-25">
      <div class="circle--filter circle--secondary--module">
        <h4> Project Filter</h4>
        <ul class="circle--filter--list">
        {% for project in projects %}
          {% for position in project.projectposition_set.all %}
          {% if position.title and position.information %}
          <li><a href="{% url 'profile:filter-projects' position %}">{{ position.title }}</a></li>
          {% endif %}
          {% endfor %}
        {% endfor %}
        </ul>
      </div>
    </div>

    <div class="grid-70 grid-push-5">
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Project Title</th>
            <th class="circle--cell--right">Project Needs</th>
          </tr>
        </thead>
        <tbody>
        {% for project in projects %}
          {% for position in project.projectposition_set.all|slice:":1" %}
            {% if position.title and position.information %}
          <tr class="clickable-row">
            <td>
              <h3><a href="{% url 'profile:project' pk=project.pk %}">{{ project.title }}</a></h3>
            </td>
            <td class="circle--cell--right">
              <span class="secondary-label"> <a href="{% url 'profile:project' pk=project.pk %}">{{ position.title }}</a></span>
              {% endif %}
            {% endfor %}
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

team_builder/templates/layout.html
{% load staticfiles %}

<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>Circle</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONTS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href="{% static 'css/global.css' %}">

  <!-- JS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
  <script type="text/javascript" src="{% static 'js/autogrow.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/global.js' %}"></script>


</head>

<body>
  <form method='GET' action="{% url 'profile:search_project' %}">
  <header class="circle--header">
    <div class="bounds">
      <div class="circle--fluid">
        <div class="circle--fluid--cell">
          <h1 class="hide-text circle--logo"><a class="logo" href="{% url 'index' %}">Circle</a></h1>
        </div>
        <div class="circle--fluid--cell circle--fluid--primary">
          <div class="circle--search">
            <input type="text" name='query' placeholder="Search Projects..." />
            <button>
              <svg version="1.1" class="search" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 12 12" xml:space="preserve">
                <path d="M12,10.6L8.3,6.9C8.7,6.2,9,5.4,9,4.5C9,2,7,0,4.5,0S0,2,0,4.5S2,9,4.5,9c0.9,0,1.7-0.3,2.4-0.7l3.7,3.7L12,10.6z M2,4.5
                C2,3.1,3.1,2,4.5,2S7,3.1,7,4.5C7,5.9,5.9,7,4.5,7S2,5.9,2,4.5z"/>
              </svg>
            </button>
          </div>
        </div>
        <div class="circle--fluid--cell circle--fluid--secondary">
          <nav>
            <ul class="circle--inline">
              {% if not user.is_authenticated %}
              <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
              <li><a href="{% url 'login' %}">Sign In</a></li>
              {% else %}
              <li><a href="{% url 'profile:my_profile' pk=request.user.pk %}">{{ user.username }}</a></li>
              <li><a href="{% url 'profile:notifications' %}">Notifications</a></li>

              <li><a href="{% url 'accounts:signout' %}">Sign Out</a></li>

              {% endif %}
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </header>

  <div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
        {% if user.is_authenticated %}
        <li><a {% if 'applications' in request.path %} class="selected" {% endif %} href="{% url 'profile:all_applications' %}">Applications</a></li>
        <li><a {% if 'profile' in request.path and 'applications' not in request.path%} class="selected" {% endif %} href="{% url 'profile:my_profile' pk=request.user.pk %}">Profile</a></li>
        {% endif %}
      </ul>
    </nav>
  </div>

</form>
  {% block body_content %}{% endblock %}

</body>